# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stures', '0002_auto_20171021_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cgpa',
        ),
        migrations.AddField(
            model_name='resource',
            name='author',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='resource',
            name='topic',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
