# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stures', '0005_resource_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='author',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='resource',
            name='content',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='resource',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='topic',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
